[package]
name = "wkpatch-cli"
version = "0.1.0"
authors = ["Emil Hesslow <hesslow@gmail.com>"]
edition = "2018"
default-run = "wkpatch"

[[bin]]
name = "wkpatch"
path = "src/main.rs"

[dependencies]
wkpatch = { path = "../wkpatch" }
clap = "2.33"